name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  job_1:
    runs-on: ubuntu-latest
    env :
      area : shikoku
    steps:
      - name: step1
        uses: actions/checkout@v2
      - name : build1
        run: |
          wget https://github.com/julien-noblet/download-geofabrik/releases/download/v2.5.0/download-geofabrik_2.5.0_Linux_x86_64.tar.gz
          tar vxfz ./download-geofabrik_2.5.0_Linux_x86_64.tar.gz
          ./download-geofabrik download $area
          docker volume create openstreetmap-data
          docker run \
            ―v ./$area.osm.pbf:/data.osm.pbf \
            -v openstreetmap-data:/var/lib/postgresql/12/main \
            overv/openstreetmap-tile-server \
            import
